:: Use only under MIT License
:: If you want to Publish a modified Version please mention the Original Creator PIRANY and link the GitHub Repo

@if not defined debug_assist (@ECHO OFF) else (@echo on)
@title Data Spammer
color 2
if "%noerror2%" == "true" (
    goto noerr
) else (
    start.bat
)

:noerr
if "%settingsmainscriptvar%" == "1" goto setting

SETLOCAL EnableDelayedExpansion
SET $Echo=FOR %%I IN (1 2) DO IF %%I==2 (SETLOCAL EnableDelayedExpansion ^& FOR %%A IN (^^^!Text:""^^^^^=^^^^^"^^^!) DO ENDLOCAL ^& ENDLOCAL ^& ECHO %%~A) ELSE SETLOCAL DisableDelayedExpansion ^& SET Text=
SETLOCAL DisableDelayedExpansion

setlocal enabledelayedexpansion
set "file=settings.txt"
set nr=0
for /l %%i in (1,1,100) do (
    set "line%%i="
)
for /f "delims=" %%a in (%file%) do (
    set /a "nr+=1"
    set "line!nr!=%%a"
)
set "insdonevar1=!line1!"
set "stdfile=!line2!"
set "stdrc1=!line3!"
if not defined devtools (goto menu) else (goto dtd)

:menu
cls
%$Echo% "   ____        _        ____                                            _           ____ ___ ____      _    _   ___   __
%$Echo% "  |  _ \  __ _| |_ __ _/ ___| _ __   __ _ _ __ ___  _ __ ___   ___ _ __| |__  _   _|  _ \_ _|  _ \    / \  | \ | \ \ / /
%$Echo% "  | | | |/ _` | __/ _` \___ \| '_ \ / _` | '_ ` _ \| '_ ` _ \ / _ \ '__| '_ \| | | | |_) | || |_) |  / _ \ |  \| |\ V / 
%$Echo% "  | |_| | (_| | || (_| |___) | |_) | (_| | | | | | | | | | | |  __/ |  | |_) | |_| |  __/| ||  _ <  / ___ \| |\  | | |  
%$Echo% "  |____/ \__,_|\__\__,_|____/| .__/ \__,_|_| |_| |_|_| |_| |_|\___|_|  |_.__/ \__, |_|  |___|_| \_\/_/   \_\_| \_| |_|  
%$Echo% "                             |_|                                              |___/                                     



@ping -n 1 localhost> nul
echo Made by PIRANY (pirany on discord)
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [1] Info
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Start
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] Cancel
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [4] Credits/Contact
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [5] Settings
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [6] Autostart/Desktop Icon
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [7] Check for Updates
echo.
echo.
set /p menu1=Choose an Option from Above:

If %menu1% == 1 goto info
If %menu1% == 2 goto start
If %menu1% == 3 goto cancel
If %menu1% == 4 goto credits
If %menu1% == 5 goto setting
If %menu1% == 6 goto autostartdeskic
If %menu1% == 7 goto checkgitupdt
goto menu

:checkgitupdt
set "owner=PIRANY1"
set "repo=DataSpammer"
set "api_url=https://api.github.com/repos/%owner%/%repo%/releases/latest"
echo Fetching Git Url....
@ping -n 1 localhost> nul
for /f "usebackq tokens=*" %%i in (`curl -s %api_url% ^| jq -r ".tag_name"`) do (set "latest_version=%%i")
if %latest_version% == v2 (goto UpToDate) else (start.bat)

:UpToDate
@ping -n 1 localhost> nul
echo The Version you are currently Using is the newest one (%latest_version%)
pause 
goto menu


:info
cls
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo No liability for any Damages on your Software.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo If you want to use this Script on a Server you have to be able to write something in the Folder you want to use.
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo [1] Go back
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Exit
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
set /p menu2=Choose an Option from Above:
If %menu2% == 1 goto menu
If %menu2% == 2 goto cancel
goto info

:credits
cls 
echo.
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo This Script is made by PIRANY for Educational Use only.
@ping -n 1 localhost> nul
echo The whole Code is made by PIRANY  
@ping -n 1 localhost> nul
echo ASCII-Art was generated by TAAG (Text to ASCII Art Generator)
@ping -n 1 localhost> nul
echo If you found any Bugs/Glitches or have a Problem With this software please 
@ping -n 1 localhost> nul
echo Create a Issue on the Github-Repo
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo [1] Go back
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Open the Github-Repo
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] Exit
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
set /p menu3=Choose an Option from Above:
If %menu3% == 1 goto menu
If %menu3% == 3 goto cancel
If %menu3% == 2 goto GitRepo
goto credits

:GitRepo
cls 
echo Opening Github-Repo 
@ping -n 1 localhost> nul
echo 3
@ping -n 1 localhost> nul
@ping -n 1 localhost> nul
echo 2
@ping -n 1 localhost> nul
@ping -n 1 localhost> nul
echo 1
@ping -n 1 localhost> nul
@ping -n 1 localhost> nul
echo Opening...
start "" "https://github.com/PIRANY1/DataSpammer"
goto credits

:setting
cls 
echo ========
echo Settings
echo ========
echo.
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo [1] Standart Filename (Will have a Number behind.)
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Standard Directory to Spam(idk why you would need this but here you go)
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] Go back
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul


set /p menu4=Choose an Option from Above:
If %menu4% == 1 goto filenamechange
If %menu4% == 2 goto stddirectorycrash
If %menu4% == 3 goto menu
goto setting

:filenamechange
cls 
echo The Filename cant have the following Character(s):\ / : * ? " < > |"
set /p mainfilename=Type in the Filename you want to use.
setlocal enabledelayedexpansion
set "file=settings.txt"
set "tmpfile=temp.txt"
set linenumber=0
(for /f "tokens=*" %%a in (!file!) do (
    set /a "linenumber+=1"
    if !linenumber! equ 2 (
        echo !mainfilename!
    ) else (
        echo %%a
    )
)) > !tmpfile!
move /y !tmpfile! !file!
echo The Standart Filename was saved!
cls
goto setting


:stddirectorycrash
cls 
echo.
echo.
set /p directory0=Type Your Directory Here:
setlocal enabledelayedexpansion
set "setfile=settings.txt"
set "tmpfile=temp.txt"
set "lineCounter=0"

(
  for /f "tokens=*" %%a in (!setfile!) do (
    set /a "lineCounter+=1"
    if !lineCounter! equ 3 (
      echo !directory0!
    ) else (
      echo %%a
    )
  )
) > !tmpfile!
move /y !tmpfile! !setfile!
echo The Directory was saved!
cls
goto setting


:autostartdeskic
echo.
cls
echo.
echo ==================
echo Autostart/Desktopicon Settings
echo ==================
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [1] Setup 
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Delete Autostart
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] Delete DesktopIcon
echo.
@ping -n 1 localhost> nul
echo [4] Back
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [5] Settings
echo.
echo.
set /p menu000=Choose an Option from Above:

If %menu000% == 1 goto autostartsetup
If %menu000% == 2 goto autostartdelete
If %menu000% == 4 goto menu
If %menu000% == 3 goto desktopicdel
If %menu000% == 5 goto autostartdesktsett
goto autostartdeskic

:autostartsetup
echo This Setup will lead you trough the Autostart/Desktopicon Setup.
@ping -n 1 localhost> nul
echo If you are not sure what that is please take a look at the Information.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [1] Start Setup for Autostart
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Start Setup for DesktopIcon
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] View Information
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [4] Go Back
@ping -n 1 localhost> nul
echo.
set /p menu123134=Choose an Option from Above:

If %menu123134% == 3 goto viewdocs 
If %menu123134% == 1 goto autostartsetupconfyy
If %menu123134% == 4 goto autostart
If %menu123134% == 2 goto desktopiconsetup
goto autostartsetup

:viewdocs 
@ping -n 1 localhost> nul
echo If you put for example Links or Programms into your Autostart Folder 
@ping -n 1 localhost> nul
echo They will automaticly launch if you boot your Device.
@ping -n 1 localhost> nul
echo Your System cant be more vulnerable if you do this.
@ping -n 1 localhost> nul
echo You can create an Desktop Icon too if you dont want the Script to open 
@ping -n 1 localhost> nul
echo Every time you boot.
@ping -n 1 localhost> nul
echo Please note that if you change the Directory you also need to change it in the Autostart Settings.
@ping -n 1 localhost> nul
echo [1] Go back
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Open Desktop Icon Setup.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] Open AutostartSetup
echo.
@ping -n 1 localhost> nul
set /p viewdocsmenu=Choose an Option from above:

If %viewdocsmenu% == 1 goto autostartsetup
If %viewdocsmenu% == 2 goto desktopiconsetup
If %viewdocsmenu% == 3 goto autostartsetupconfyy
goto viewdocs

:autostartdelete
:echo Please provide the Letter of the Drive that has Windows installed. Often it is C but it can be for example G too
@ping -n 1 localhost> nul
set /p autostartdriveletter=Please type the Letter here:
@ping -n 1 localhost> nul
cd %autostartdriveletter%:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
del autostart.bat
cd %~dp0

:autostartsetupconfyy
echo Please provide the Letter of the Drive that has Windows installed. Often it is C but it can be for example G too
@ping -n 1 localhost> nul
set /p autostartdriveletter=Please type the Letter here:
@ping -n 1 localhost> nul
echo The Setup for Autostart is now starting...
cd %autostartdriveletter%:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup
@ping -n 1 localhost> nul
echo. > DataSpammer.bat
set "varlinkauto=%~dp0"
(
echo @echo off
echo cd %varlinkauto%
start.bat
) > autostart.bat
cd %~dp0


:desktopiconsetup
echo. > DataSpammer.bat
set "varlinkauto=%~dp0"
(
echo @echo off
echo cd %varlinkauto%
start.bat
) > DataSpammer.bat
                                                                                                    

:autostartdesktsett
echo.
@ping -n 1 localhost> nul
echo If you have moved the Directory please Delete the Autostart and Then Set it up new
@ping -n 1 localhost> nul
pause
goto autostartdeskic


:start
cls
set "verify=%random%"
echo Please Verify that you want to use a Spam Method.
echo Please have in Mind that this can make your Installation Unusable.
echo Please enter %verify% in the Field Below
set /p verifyans=Type %verify%:
if "%verifyans%"=="%verify%" (
    goto start187
) else (
    goto start
)

:start187
echo Choose the Method you want to use:
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [1] .txt Spam in custom Directory
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Desktop Icon Spam
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [3] Go Back
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo.
set /p spammethod=Choose an Option from Above:

If %spammethod% == 1 goto txtspamchose
If %spammethod% == 2 goto deskiconspam
If %spammethod% == 3 goto menu
goto start187

:deskiconspam
@ping -n 1 localhost> nul
echo This Method will Spam your Desktop with Files
@ping -n 1 localhost> nul
echo You can customise four things here. 
@ping -n 1 localhost> nul
echo 1:Filename
@ping -n 1 localhost> nul
echo 2:Format of the File (for example .txt or .bat)
@ping -n 1 localhost> nul
echo 3:The Text in the File
@ping -n 1 localhost> nul
echo 4:Count of Files
@ping -n 1 localhost> nul
echo.
echo [1] Start 
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Go Back
@ping -n 1 localhost> nul
echo.
echo.
set /p menu1877=Choose an Option from Above:
If %menu1877% == 2 goto start
If %menu1877% == 1 goto deskiconspam1
goto deskiconspam

:deskiconspam1
echo How Should the Files be named?
@ping -n 1 localhost> nul
echo The Filename cant include one of the following Character(s):\ / : * ? " < > |"
@ping -n 1 localhost> nul
set /p "deskiconspamname=Choose a Filename:"
goto deskiconspam2

:deskiconspam2
echo Now Choose the Format of the File
@ping -n 1 localhost> nul
echo If you are not sure type txt
@ping -n 1 localhost> nul
echo Please not include the dot
@ping -n 1 localhost> nul
set /p "deskiconspamformat=Choose the Format:"
goto deskiconspam3

:deskiconspam3
echo Now Choose the Content the File should include
@ping -n 1 localhost> nul
set /p "deskiconspamcontent=Type something in:"
goto deskiconspam4

:deskiconspam4
echo Now Choose how many files should be created 
@ping -n 1 localhost> nul
echo Leave empty if you want infinite.
@ping -n 1 localhost> nul
set /p "deskiconspamamount=Type a Number:"
goto deskiconspamwdata

:deskiconspamwdata
echo All set. 
@ping -n 1 localhost> nul
echo Please confirm that you want to Spam your Desktop.
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo [y] Yes
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [n] No, Cancel
@ping -n 1 localhost> nul
set /p deskicspamconf11=Choose an Option from Above:
If %deskicspamconf11% == y goto deskiconspamconfdata
If %deskicspamconf11% == n goto menu
goto deskiconspamwdata

:deskiconspamconfdata
set "assetcount=1"
:assetcounttop
color 02
@ping -n 1 localhost> nul
echo Loading Assets(%assetcount%/32)
set /a "assetcount+=1"
If %assetcount% == 33 (goto deskiconspamsetdonestart) else (goto assetcounttop)


:deskiconspamsetdonestart
cls
color 02
echo The Desktopiconspammer is about to start....
@ping -n 2 localhost> nul
echo 3 Seconds Left
echo If you want to stop this, Simply close the CMD-Window
@ping -n 2 localhost> nul
echo 2 Seconds Left
@ping -n 2 localhost> nul
echo 1 Seconds Left
@ping -n 1 localhost> nul
echo Starting.....
cd %userprofile%\Desktop
if not defined deskiconspamamount (
    goto infinitespam
) else (
    goto limitedspam
)

exit
:infinitespam
:deskspamtop
echo %deskiconspamcontent% > %deskiconspamname%.%deskiconspamformat%
goto deskspamtop
exit

:limitedspam
color 02
set "deskspamlimitedvar=1"
:limitedspam1
If %deskspamlimitedvar% == %deskiconspamamount% (goto done2) else (goto limitedspam2)
:limitedspam2
echo Created %deskspamlimitedvar% File(s)
echo %deskiconspamcontent% > %deskiconspamname%%deskspamlimitedvar%.%deskiconspamformat%
set /a "deskspamlimitedvar+=1"
goto limitedspam1

:txtspamchose
if defined stdrc1 (
    cd %stdrc1%
    goto nameset
) else (
    goto novarset
)

:novarset
cls
echo Please enter the Directory of the Folder/Server you want to Spam.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo You can find the Directory by Clicking on the Path in you Explorer (on top) and copy it in here. 
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo It should look something like this: C:\User\Dokuments\SpamFolder
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo You can use your User Directory if you are using a Server. This works in most Cases but it sometimes doesnt work. Why dont you try?
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo [1] Use User Directory
@ping -n 1 localhost> nul
echo. 
@ping -n 1 localhost> nul
echo [2] Enter a Directory
@ping -n 1 localhost> nul
set /p menu5=Choose an Option from Above:
If %menu5% == 1 goto userdrc
If %menu5% == 2 goto manualcd

:userdrc 
cd %userprofile%

:manualcd
echo.
echo.
set /p directory1=Type Your Directory Here:

cd %directory1%

if %ERRORLEVEL% neq 0 (
    echo There was an Error. Please check if the Directory is correct or retry later. 
) else (
    echo The Directory was Correct!
    goto nameset
)

:nameset
if defined stdfile (
    goto cddone
) else (
    goto nameset2
)

:nameset2
cls
echo Now You have to choose a filename. It can be anything as long as the 
echo Filename doesnt have the following Character(s):\ / : * ? " < > |"
set /p stdfile=Type in the Filename you want to use.
setlocal enabledelayedexpansion
goto timerask

:timerask
cls
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo Do you want to set how many files should be created?
@ping -n 1 localhost> nul
echo If you choose No the script will run for eternity.
@ping -n 1 localhost> nul
set /p menu6=Yes[y]  No [n]:
If %menu6% == y goto timerset
If %menu6% == n goto cddone
goto timerask

:timerset 
cls
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo How many Files should be created?
set /p filecount=Type a Number:
goto cddone

:cddone
cls
echo. 
echo.
echo Please confirm.
pause
echo Loading...
@ping -n 2 localhost> nul
echo 5 Seconds left
@ping -n 2 localhost> nul
echo 4 Seconds left
@ping -n 2 localhost> nul
echo 3 Seconds left
@ping -n 2 localhost> nul
echo 2 Seconds left
@ping -n 2 localhost> nul
echo 1 Second left
@ping -n 2 localhost> nul
echo Starting......
echo If you want to stop this script simply close the Command Windows or press ALT F4
:top
set /a x+=1
type nul > %stdfile%%x%.txt
echo Created %x% File(s).
if %x% equ %filecount% (
    goto done
    cls
) else (
    goto top
    cls
)
cls

:done
echo.
%$Echo% "   ____        _        ____                                            _           ____ ___ ____      _    _   ___   __
%$Echo% "  |  _ \  __ _| |_ __ _/ ___| _ __   __ _ _ __ ___  _ __ ___   ___ _ __| |__  _   _|  _ \_ _|  _ \    / \  | \ | \ \ / /
%$Echo% "  | | | |/ _` | __/ _` \___ \| '_ \ / _` | '_ ` _ \| '_ ` _ \ / _ \ '__| '_ \| | | | |_) | || |_) |  / _ \ |  \| |\ V / 
%$Echo% "  | |_| | (_| | || (_| |___) | |_) | (_| | | | | | | | | | | |  __/ |  | |_) | |_| |  __/| ||  _ <  / ___ \| |\  | | |  
%$Echo% "  |____/ \__,_|\__\__,_|____/| .__/ \__,_|_| |_| |_|_| |_| |_|\___|_|  |_.__/ \__, |_|  |___|_| \_\/_/   \_\_| \_| |_|  
%$Echo% "                             |_|                                              |___/                                                                                                                                     

@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo The Script Created %filecount% Files.
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo Do you want to Close the Script or Go to the Menu?
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [1] Close
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Menu
echo.
@ping -n 1 localhost> nul
set /p menu9=Choose an Option from Above:
If %menu9% == 1 goto cancel
If %menu9% == 2 goto menu
goto done

:done2
echo.
%$Echo% "   ____        _        ____                                            _           ____ ___ ____      _    _   ___   __
%$Echo% "  |  _ \  __ _| |_ __ _/ ___| _ __   __ _ _ __ ___  _ __ ___   ___ _ __| |__  _   _|  _ \_ _|  _ \    / \  | \ | \ \ / /
%$Echo% "  | | | |/ _` | __/ _` \___ \| '_ \ / _` | '_ ` _ \| '_ ` _ \ / _ \ '__| '_ \| | | | |_) | || |_) |  / _ \ |  \| |\ V / 
%$Echo% "  | |_| | (_| | || (_| |___) | |_) | (_| | | | | | | | | | | |  __/ |  | |_) | |_| |  __/| ||  _ <  / ___ \| |\  | | |  
%$Echo% "  |____/ \__,_|\__\__,_|____/| .__/ \__,_|_| |_| |_|_| |_| |_|\___|_|  |_.__/ \__, |_|  |___|_| \_\/_/   \_\_| \_| |_|  
%$Echo% "                             |_|                                              |___/                                     
                                                                                              

@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo The Script Created %deskspamlimitedvar% Files.
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo Do you want to Close the Script or Go to the Menu?
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [1] Close
echo.
@ping -n 1 localhost> nul
echo.
@ping -n 1 localhost> nul
echo [2] Menu
echo.
@ping -n 1 localhost> nul
set /p menu9=Choose an Option from Above:
If %menu9% == 1 goto cancel
If %menu9% == 2 goto menu
goto done2


:cancel 
exit
exit

:dtd
set /p dtd1=.:.
%dtd1%